# Site settings
title: Sebastián Freille
email: sebastian.freille@gmail.com
description: >-
  Academic economist at Universidad Nacional de Córdoba. 
  Research in public economics, political economy, sub-national elections, 
  and institutional corruption.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sfreille.github.io"

# Social/academic links
github_username: sfreille
google_scholar_id: MVhxy_sAAAAJ
orcid_id: 0000-0002-1458-0929
x_id: sebafreille

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
